[build]
  functions = "netlify/functions"
  publish = "."

# Esto habilita CORS básico para dev rápido;
# en producción puedes restringirlo a tu dominio
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

